CREATE TABLE IF NOT EXISTS `hlmmasters`.`signup` (
  `idsignup` BIGINT(100) NOT NULL,
  `branchName` VARCHAR(45) NULL DEFAULT NULL,
  `userName` VARCHAR(45) NULL DEFAULT NULL,
  `password` LONGTEXT NULL DEFAULT NULL,
  `emailid` VARCHAR(100) NULL DEFAULT NULL,
  `referalCode` VARCHAR(45) NULL,
  `passwordExpire` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `mustChangePassword` TINYINT NULL DEFAULT 0,
  `loggedin` TINYINT NULL DEFAULT 0,
  `userlock` TINYINT NULL DEFAULT 0,
  `loginfailed` TINYINT NULL DEFAULT 0,
  `createdDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `activeStatus` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idsignup`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3