CREATE TABLE IF NOT EXISTS `default`.`tenders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `companyId` BIGINT NULL,
  `subCategoryId` BIGINT NULL,
  `tittle` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `location` VARCHAR(100) NULL,
  `deadLine` DATETIME NULL,
  `tenderStatus` VARCHAR(45) NULL DEFAULT 'OPEN',
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB