CREATE TABLE IF NOT EXISTS `hlmmasters`.`employees` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `employeeCode` BIGINT NULL,
  `employeePhoto` LONGBLOB NULL,
  `name` VARCHAR(50) NULL,
  `gender` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `bloodGroup` VARCHAR(45) NULL,
  `motherTongue` VARCHAR(45) NULL,
  `readingLanguage` LONGTEXT NULL,
  `speakingLanguage` LONGTEXT NULL,
  `emailId` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `emergencyContact` VARCHAR(45) NULL,
  `doj` DATE NULL,
  `designation` LONGTEXT NULL,
  `department` LONGTEXT NULL,
  `workingStatus` VARCHAR(45) NULL,
  `dateOfExit` DATE NULL,
  `preparedBy` VARCHAR(255) NULL,
  `preparedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `approvedBy` VARCHAR(255) NULL,
  `approvedAt` DATETIME NULL,
  `stage` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
